// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhIYAPjDEVcxt8jHiVR8fD_jBSoBk05I0',
    appId: '1:284683212345:web:a7fd441fe1bd3ddb8bdfe8',
    messagingSenderId: '284683212345',
    projectId: 'nena-403504',
    authDomain: 'nena-403504.firebaseapp.com',
    databaseURL: 'https://nena-403504-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nena-403504.firebasestorage.app',
    measurementId: 'G-RJM9TSZ42W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYO8ABxc3Y75LTwmxh25MrAutkioccaZE',
    appId: '1:284683212345:android:72368d1da15c0b078bdfe8',
    messagingSenderId: '284683212345',
    projectId: 'nena-403504',
    databaseURL: 'https://nena-403504-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nena-403504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATrU7AMKZxFDi7DqJt1hdmOw5g_0jCxCM',
    appId: '1:284683212345:ios:472cbe4915a6e0f68bdfe8',
    messagingSenderId: '284683212345',
    projectId: 'nena-403504',
    databaseURL: 'https://nena-403504-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nena-403504.firebasestorage.app',
    androidClientId: '284683212345-tsajn0ofajmlicssqerfgjemo0gq3qpf.apps.googleusercontent.com',
    iosClientId: '284683212345-evju881h0dnr060eqoji14f0mnmjf99k.apps.googleusercontent.com',
    iosBundleId: 'com.pocketwise.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATrU7AMKZxFDi7DqJt1hdmOw5g_0jCxCM',
    appId: '1:284683212345:ios:472cbe4915a6e0f68bdfe8',
    messagingSenderId: '284683212345',
    projectId: 'nena-403504',
    databaseURL: 'https://nena-403504-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nena-403504.firebasestorage.app',
    androidClientId: '284683212345-tsajn0ofajmlicssqerfgjemo0gq3qpf.apps.googleusercontent.com',
    iosClientId: '284683212345-evju881h0dnr060eqoji14f0mnmjf99k.apps.googleusercontent.com',
    iosBundleId: 'com.pocketwise.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJQ_BclE_DCxFLigJXFLzLKDyTTqADQT0',
    appId: '1:284683212345:web:05c3dab478b92b0a8bdfe8',
    messagingSenderId: '284683212345',
    projectId: 'nena-403504',
    authDomain: 'nena-403504.firebaseapp.com',
    databaseURL: 'https://nena-403504-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nena-403504.firebasestorage.app',
    measurementId: 'G-4L2TJKDGXC',
  );
}
